name: Run WPScan check

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run PHP Script
        uses: docker://php:7.4-cli
        env:
          WPSCAN_TOKEN: ${{ secrets.WPSCAN_TOKEN }}
          WP_CONTENT_PATH: ${{ secrets.WP_CONTENT_PATH }}
        with:
          args: php check-wpscan.php
